version: "3.9"

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - DB_TYPE=${N8N_DATABASE_TYPE}
      - DB_POSTGRESDB_HOST=${N8N_DATABASE_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${N8N_DATABASE_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${N8N_DATABASE_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${N8N_DATABASE_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_DATABASE_POSTGRESDB_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - N8N_API_BASE_URL=${N8N_API_BASE_URL}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_LOG_LEVEL=${N8N_LOG_LEVEL}
    ports:
      - "${N8N_PORT}:${N8N_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - n8n_data:/home/node/.n8n

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${N8N_DATABASE_POSTGRESDB_DATABASE}
      - POSTGRES_USER=${N8N_DATABASE_POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${N8N_DATABASE_POSTGRESDB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${N8N_DATABASE_POSTGRESDB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  n8n_data:
  postgres_data:

networks:
  default:
    driver: bridge
