name: Deploy n8n with Docker Compose

on:
  push:
    branches:
      - main # Executa o pipeline ao fazer push na branch "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      # Subir os serviços com Docker Compose
      - name: Start Docker Compose
        run: |
          docker compose --env-file .env -f infra/compose.yaml up -d

      # Verificar os serviços em execução
      - name: Check running containers
        run: docker ps
